### ISSUE TITLE
Not returning phone number from fb page.

### ISSUE THREAD

**Issue by SSujitX** [wael-sudo2/facebook-page-info-scraper#38]
Tried on this page: 

https://www.facebook.com/zartaaz/

```
from facebook_page_info_scraper import FacebookPageInfoScraper

page_url = "https://www.facebook.com/zartaaz/"
scraper = FacebookPageInfoScraper(link=page_url)
page_info = scraper.get_page_info()
print(page_info)
```

output

```
scraping: Zartaaz
{'page_name': 'Zartaaz', 'page_category': "Women's clothes shop", 'email': 'mayuri2021@gmail.com', 'page_website': None, 'social_media_links': None, 'phone_number': None, 'location': 'Business Point , 1st Floor , shop No - 236 ., Islampur, Bangladesh, 1100', 'page_rate': None, 'page_review_number': None, 'page_likes': '2.7K ', 'page_followers': '2.7K ', 'following': None}
```

**Comment by wael-sudo2** [comment]
on it !!

**Comment by SSujitX** [comment]
> on it !!

also, add webdriver_manager in pip requests. It is missing.

**Comment by wael-sudo2** [comment]
@SSujitX It might be an issue related to slow page loading, causing the DOM to not fully load. I suggest trying to rescrape the link to see if that resolves the problem nothing wrong with the code

from facebook_page_info_scraper import FacebookPageInfoScraper
page_url = "https://www.facebook.com/zartaaz/"
scraper = FacebookPageInfoScraper(link=page_url)
page_info = scraper.get_page_info()
print(page_info)

response : 
`
{'page_name': 'Zartaaz', 'page_category': "Women's clothing store", 'email': 'mayuri2021@gmail.com', 'page_website': None, 'social_media_links': None, 'phone_number': '+880 1640-480550', 'location': 'Business Point , 1st Floor , shop No - 236 ., Islampur, Bangladesh, 1100', 'page_rate': None, 'page_review_number': None, 'page_likes': '2.7K ', 'page_followers': '2.7K ', 'following': None}
`

**Comment by wael-sudo2** [comment]
closed due inactivity
